export default {
  app: { name: 'श्री लता किराना स्टोर्स', subtitle: 'डिजिटल खाता' },
  nav: { dashboard: 'डैशबोर्ड', customers: 'ग्राहक', transactions: 'लेन-देन', payments: 'भुगतान', notifications: 'सूचनाएं', receipts: 'रसीदें', settings: 'सेटिंग्स' },
  actions: { logout: 'लॉग आउट', theme: 'थीम', language: 'भाषा', light: 'लाइट', dark: 'डार्क', viewAll: 'सभी देखें', addSale: 'बिक्री जोड़ें', collect: 'वसूली', addCustomer: 'ग्राहक जोड़ें', daySummary: 'दिन सारांश' },
  dashboard: { greeting: 'सुप्रभात', welcome: 'वापसी पर स्वागत है', shopFallback: 'आपकी किराना दुकान', today: 'आज', sales: 'आज की बिक्री', totalOutstanding: 'कुल बकाया', overdue: 'बकाया', customers: 'ग्राहक', pendingEntries: 'लंबित एंट्री', completeTransactions: 'बकाया ग्राहक एंट्री देखें', needsAttention: 'ध्यान आवश्यक', recentActivity: 'हाल की गतिविधि', noActivity: 'आपकी हाल की दुकान गतिविधि यहां दिखेगी।', noOverdue: 'कोई भुगतान बकाया नहीं है।', cash: 'नकद', upi: 'यूपीआई', udhar: 'उधार' },
  business: { customerBook: 'ग्राहक बही', salesBook: 'बिक्री बही', collectionBook: 'वसूली बही', loading: 'रिकॉर्ड लोड हो रहे हैं…', searchCustomers: 'नाम या मोबाइल नंबर खोजें', noCustomers: 'अभी कोई ग्राहक नहीं है।', noTransactions: 'अभी कोई बिक्री दर्ज नहीं है।', noPayments: 'इस ग्राहक के लिए कोई भुगतान नहीं है।', customerAdded: 'ग्राहक जोड़ा गया', customerUpdated: 'ग्राहक अपडेट किया गया', customerRemoved: 'ग्राहक हटाया गया', saleAdded: 'बिक्री दर्ज की गई', paymentAdded: 'भुगतान दर्ज किया गया', newCustomer: 'नया ग्राहक', editCustomer: 'ग्राहक संपादित करें', saveCustomer: 'ग्राहक सहेजें', newSale: 'बिक्री जोड़ें', saveSale: 'बिक्री दर्ज करें', newPayment: 'भुगतान लें', savePayment: 'भुगतान सहेजें', remove: 'हटाएं', removeCustomer: 'ग्राहक हटाएं', name: 'नाम', mobile: 'मोबाइल नंबर', address: 'पता', creditDays: 'उधार अवधि (दिन)', notes: 'नोट्स', customer: 'ग्राहक', chooseCustomer: 'ग्राहक चुनें', amount: 'राशि', paidAmount: 'अभी भुगतान', due: 'बकाया', addPayment: 'वसूली', selectCustomer: 'ग्राहक चुनें', saving: 'सहेज रहे हैं…', daysOverdue: 'दिन बकाया' },
  shop: { welcome: 'एक बार सेटअप', title: 'अपनी दुकान सेट करें', description: 'ग्राहक, बिक्री और भुगतान प्रबंधित करने के लिए दुकान का विवरण जोड़ें।', shopName: 'दुकान का नाम', shopNameExample: 'श्री लता किराना स्टोर्स', ownerName: 'मालिक का नाम', mobile: 'दुकान मोबाइल नंबर', address: 'दुकान का पता', addressExample: 'पुणे, महाराष्ट्र', creditPeriod: 'डिफ़ॉल्ट उधार अवधि', noCredit: 'कोई उधार नहीं', days: 'दिन', create: 'मेरी दुकान बनाएं', creating: 'दुकान बनाई जा रही है…', created: 'आपकी दुकान तैयार है!' },
  pages: { comingSoon: 'जल्द आ रहा है', modulePlaceholder: 'यह मॉड्यूल अगले निर्माण चरण के लिए तैयार है।', settings: 'सेटिंग्स' },
  auth: { loading: 'आपका खाता लोड हो रहा है…' },
}
