import { Cloud, KeyRound, Mail } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import toast from 'react-hot-toast'
import AuthShell, { Brand } from '../../components/auth/AuthShell'
import { Field, PasswordField, SubmitButton } from '../../components/auth/FormControls'
import { useAuth } from '../../context/useAuth'
import { authService } from '../../services/auth.service'
export default function LoginPage() { const [form,setForm]=useState({email:'',password:''});const [loading,setLoading]=useState(false);const {login}=useAuth();const navigate=useNavigate(); const submit=async(e)=>{e.preventDefault();if(!form.email||!form.password)return toast.error('Enter your email and password.');setLoading(true);try{await login(form);toast.success('Welcome back to your Digital Khata.');navigate('/dashboard',{replace:true})}catch(error){toast.error(authService.getErrorMessage(error))}finally{setLoading(false)}};return <AuthShell compact><div className="p-6 sm:p-8"><Brand/><form onSubmit={submit} className="space-y-4"><Field label="Email address" icon={Mail} placeholder="you@shop.com" type="email" autoComplete="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><PasswordField label="Password / PIN" placeholder="Enter your secure password" autoComplete="current-password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><div className="flex justify-end"><Link className="text-xs font-semibold text-emerald-300 transition hover:text-emerald-200" to="/forgot-password">Forgot Password?</Link></div><SubmitButton loading={loading}>LOGIN TO YOUR DIGITAL KHATA</SubmitButton></form><p className="mt-6 text-center text-sm text-slate-400">New to Shri Lata? <Link className="font-bold text-cyan-300 hover:text-cyan-200" to="/register">Register New Shop</Link></p><div className="mt-7 grid grid-cols-2 gap-2 border-t border-slate-700/60 pt-5 text-[11px] font-semibold text-slate-400"><span className="flex items-center justify-center gap-1.5"><Cloud className="size-3.5 text-emerald-400" />Secure Cloud Sync</span><span className="flex items-center justify-center gap-1.5"><KeyRound className="size-3.5 text-indigo-400" />Secure Email Links</span></div></div></AuthShell> }
