import { ArrowLeft, Mail, Phone } from 'lucide-react'
import { Link, useNavigate } from 'react-router-dom'
import { useState } from 'react'
import toast from 'react-hot-toast'
import AuthShell from '../../components/auth/AuthShell'
import { Field, PasswordField, SubmitButton } from '../../components/auth/FormControls'
import PasswordStrength from '../../components/auth/PasswordStrength'
import { authService } from '../../services/auth.service'
export default function RegisterPage(){const [form,setForm]=useState({firstName:'',lastName:'',mobileNumber:'',email:'',password:'',confirmPassword:''}),[loading,setLoading]=useState(false),navigate=useNavigate();const set=(key)=>(e)=>setForm({...form,[key]:e.target.value});const submit=async(e)=>{e.preventDefault();if(Object.values(form).some(v=>!v))return toast.error('Please complete every field.');if(form.password!==form.confirmPassword)return toast.error('Passwords do not match.');setLoading(true);try{await authService.register({...form,mobileNumber:`+91${form.mobileNumber.replace(/^\+?91/,'').replace(/\D/g,'')}`});toast.success('Registration complete. Check your inbox to verify email.');navigate(`/check-email?type=verify&email=${encodeURIComponent(form.email)}`)}catch(error){toast.error(authService.getErrorMessage(error))}finally{setLoading(false)}};return <AuthShell><div className="p-6 sm:p-8"><Link to="/login" className="mb-5 inline-flex items-center gap-1.5 text-sm font-semibold text-slate-400 transition hover:text-emerald-300"><ArrowLeft className="size-4"/>Back to login</Link><h1 className="text-2xl font-extrabold tracking-tight text-white sm:text-3xl">Shop Registration <span className="text-slate-400">/ Signup</span></h1><p className="mt-2 text-sm text-slate-400">Create your secure digital khata in a minute.</p><form onSubmit={submit} className="mt-7 space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="First name" placeholder="Shri" value={form.firstName} onChange={set('firstName')} autoComplete="given-name"/><Field label="Last name" placeholder="Lata" value={form.lastName} onChange={set('lastName')} autoComplete="family-name"/></div><Field label="Mobile number" icon={Phone} prefix="+91" placeholder="98765 43210" inputMode="tel" value={form.mobileNumber} onChange={set('mobileNumber')} autoComplete="tel"/><Field label="Email address" icon={Mail} placeholder="owner@shop.com" type="email" value={form.email} onChange={set('email')} autoComplete="email"/><div className="grid gap-4 sm:grid-cols-2"><PasswordField label="Set password" placeholder="8+ characters" value={form.password} onChange={set('password')} autoComplete="new-password"/><PasswordField label="Confirm password" placeholder="Repeat password" value={form.confirmPassword} onChange={set('confirmPassword')} autoComplete="new-password"/></div><PasswordStrength value={form.password}/><SubmitButton variant="emerald" loading={loading}>CREATE MY DIGITAL KHATA</SubmitButton></form><p className="mt-6 text-center text-sm text-slate-400">Already registered? <Link className="font-bold text-cyan-300 hover:text-cyan-200" to="/login">Login here</Link></p></div></AuthShell>}
