import { KeyRound } from 'lucide-react'
import { Link, useNavigate, useSearchParams } from 'react-router-dom'
import { useState } from 'react'
import toast from 'react-hot-toast'
import AuthShell, { Brand } from '../../components/auth/AuthShell'
import { PasswordField, SubmitButton } from '../../components/auth/FormControls'
import PasswordStrength from '../../components/auth/PasswordStrength'
import { authService } from '../../services/auth.service'
export default function ResetPasswordPage(){const [params]=useSearchParams(),navigate=useNavigate(),[password,setPassword]=useState(''),[confirmPassword,setConfirmPassword]=useState(''),[loading,setLoading]=useState(false);const submit=async(e)=>{e.preventDefault();const token=params.get('token');if(!token)return toast.error('Your reset link is missing or invalid.');if(password!==confirmPassword)return toast.error('Passwords do not match.');setLoading(true);try{const data=await authService.resetPassword({token,password,confirmPassword});toast.success(data.message);navigate('/login')}catch(error){toast.error(authService.getErrorMessage(error))}finally{setLoading(false)}};return <AuthShell compact><div className="p-6 sm:p-8"><Brand small/><div className="text-center"><KeyRound className="mx-auto size-9 text-indigo-400"/><h1 className="mt-3 text-2xl font-extrabold text-white">Set new password</h1><p className="mt-2 text-sm text-slate-400">Choose a strong password to keep your shop data secure.</p></div><form onSubmit={submit} className="mt-7 space-y-4"><PasswordField label="New password" placeholder="Create a strong password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/><PasswordStrength value={password}/><PasswordField label="Confirm new password" placeholder="Repeat your new password" value={confirmPassword} onChange={e=>setConfirmPassword(e.target.value)} autoComplete="new-password"/><SubmitButton loading={loading}>SAVE NEW PASSWORD</SubmitButton></form><p className="mt-6 text-center text-sm text-slate-400"><Link to="/login" className="font-bold text-cyan-300 hover:text-cyan-200">Back to login</Link></p></div></AuthShell>}
