import { Search, UserPlus, UsersRound, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { businessService } from '../services/business.service'
import { getApiError } from '../api/client'
import { useLanguage } from '../context/useLanguage'

const empty = { name: '', mobileNumber: '', address: '', notes: '', creditPeriod: '' }
export default function CustomersPage() {
  const { t } = useLanguage(); const [customers, setCustomers] = useState([]); const [query, setQuery] = useState(''); const [form, setForm] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const load = async (term = '') => { setLoading(true); try { const result = term.trim().length >= 2 ? await businessService.searchCustomers(term) : await businessService.customers({ limit: 100 }); setCustomers(Array.isArray(result) ? result : result.customers) } catch (e) { toast.error(getApiError(e)) } finally { setLoading(false) } }
  useEffect(() => { const timer = window.setTimeout(() => { load() }, 0); return () => window.clearTimeout(timer) }, [])
  const search = (value) => { setQuery(value); window.clearTimeout(search.timer); search.timer = window.setTimeout(() => load(value), 250) }
  const save = async (event) => { event.preventDefault(); setSaving(true); try { const payload = { ...form, creditPeriod: form.creditPeriod === '' ? undefined : Number(form.creditPeriod) }; if (form._id) await businessService.updateCustomer(form._id, payload); else await businessService.createCustomer(payload); toast.success(form._id ? t('business.customerUpdated') : t('business.customerAdded')); setForm(null); load(query) } catch (e) { toast.error(getApiError(e)) } finally { setSaving(false) } }
  const remove = async (customer) => { if (!window.confirm(`${t('business.removeCustomer')} ${customer.name}?`)) return; try { await businessService.removeCustomer(customer._id); toast.success(t('business.customerRemoved')); load(query) } catch (e) { toast.error(getApiError(e)) } }
  return <section className="business-page"><header className="business-heading"><div><p>{t('business.customerBook')}</p><h2>{t('nav.customers')}</h2></div><button className="action-button" onClick={() => setForm(empty)}><UserPlus size={18}/>{t('actions.addCustomer')}</button></header><label className="search-box"><Search size={18}/><input value={query} onChange={e => search(e.target.value)} placeholder={t('business.searchCustomers')} /></label><div className="record-list">{loading ? <div className="state-card">{t('business.loading')}</div> : customers.length ? customers.map(customer => <article className="record-card" key={customer._id}><button className="record-main" onClick={() => setForm({ ...customer, creditPeriod: customer.creditPeriod ?? '' })}><span className="avatar">{customer.name[0]}</span><span><strong>{customer.name}</strong><small>{customer.mobileNumber}{customer.address ? ` · ${customer.address}` : ''}</small></span></button><button className="text-danger" onClick={() => remove(customer)}>{t('business.remove')}</button></article>) : <div className="state-card"><UsersRound size={28}/><p>{t('business.noCustomers')}</p></div>}</div>{form && <div className="sheet-backdrop"><form className="entry-sheet" onSubmit={save}><button type="button" className="sheet-close" onClick={() => setForm(null)}><X size={20}/></button><h2>{form._id ? t('business.editCustomer') : t('business.newCustomer')}</h2><label>{t('business.name')}<input required value={form.name} onChange={e => setForm({...form,name:e.target.value})}/></label><label>{t('business.mobile')}<input required inputMode="tel" value={form.mobileNumber} onChange={e => setForm({...form,mobileNumber:e.target.value})}/></label><label>{t('business.address')}<input value={form.address || ''} onChange={e => setForm({...form,address:e.target.value})}/></label><label>{t('business.creditDays')}<input type="number" min="0" max="365" value={form.creditPeriod} onChange={e => setForm({...form,creditPeriod:e.target.value})}/></label><label>{t('business.notes')}<textarea value={form.notes || ''} onChange={e => setForm({...form,notes:e.target.value})}/></label><button className="action-button wide" disabled={saving}>{saving ? t('business.saving') : t('business.saveCustomer')}</button></form></div>}</section>
}
