import { BanknoteArrowDown, Plus, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { businessService } from '../services/business.service'
import { getApiError } from '../api/client'
import { useLanguage } from '../context/useLanguage'

const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN')}`
export default function PaymentsPage() {
  const { t } = useLanguage(); const [customers, setCustomers] = useState([]); const [payments, setPayments] = useState([]); const [selected, setSelected] = useState(''); const [form, setForm] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const loadCustomers = async () => { setLoading(true); try { const result = await businessService.customers({ limit: 100 }); setCustomers(result.customers) } catch (e) { toast.error(getApiError(e)) } finally { setLoading(false) } }
  useEffect(() => { const timer = window.setTimeout(() => { loadCustomers() }, 0); return () => window.clearTimeout(timer) }, [])
  const choose = async (id) => { setSelected(id); if (!id) return setPayments([]); try { setPayments(await businessService.paymentsForCustomer(id)) } catch (e) { toast.error(getApiError(e)) } }
  const save = async (event) => { event.preventDefault(); setSaving(true); try { await businessService.createPayment({ ...form, customerId: selected, amount: Number(form.amount) }); toast.success(t('business.paymentAdded')); setForm(null); choose(selected) } catch (e) { toast.error(getApiError(e)) } finally { setSaving(false) } }
  return <section className="business-page"><header className="business-heading"><div><p>{t('business.collectionBook')}</p><h2>{t('nav.payments')}</h2></div><button className="action-button" disabled={!selected} onClick={() => setForm({ amount: '', method: 'CASH', notes: '' })}><Plus size={18}/>{t('business.addPayment')}</button></header><label className="select-customer">{t('business.selectCustomer')}<select value={selected} onChange={e => choose(e.target.value)}><option value="">{t('business.chooseCustomer')}</option>{customers.map(customer => <option key={customer._id} value={customer._id}>{customer.name} · {customer.mobileNumber}</option>)}</select></label><div className="record-list">{loading ? <div className="state-card">{t('business.loading')}</div> : selected && (payments.length ? payments.map(payment => <article className="transaction-card" key={payment._id}><div className="transaction-icon payment"><BanknoteArrowDown size={19}/></div><div><strong>{payment.method}</strong><small>{new Date(payment.paymentDate).toLocaleDateString()}</small></div><div className="transaction-value"><strong>{money(payment.amount)}</strong>{payment.notes && <small>{payment.notes}</small>}</div></article>) : <div className="state-card"><BanknoteArrowDown size={28}/><p>{t('business.noPayments')}</p></div>)}</div>{form && <div className="sheet-backdrop"><form className="entry-sheet" onSubmit={save}><button type="button" className="sheet-close" onClick={() => setForm(null)}><X size={20}/></button><h2>{t('business.newPayment')}</h2><label>{t('business.amount')}<input required type="number" min="0.01" inputMode="decimal" value={form.amount} onChange={e => setForm({...form,amount:e.target.value})}/></label><div className="type-grid">{['CASH','UPI'].map(method => <button type="button" className={form.method === method ? 'selected' : ''} key={method} onClick={() => setForm({...form,method})}>{method}</button>)}</div><label>{t('business.notes')}<textarea value={form.notes} onChange={e => setForm({...form,notes:e.target.value})}/></label><button className="action-button wide" disabled={saving}>{saving ? t('business.saving') : t('business.savePayment')}</button></form></div>}</section>
}
