import { Plus, ReceiptText, X } from 'lucide-react'
import { useEffect, useState } from 'react'
import toast from 'react-hot-toast'
import { businessService } from '../services/business.service'
import { getApiError } from '../api/client'
import { useLanguage } from '../context/useLanguage'

const fresh = { customerId: '', totalAmount: '', paidAmount: '', transactionType: 'UDHAR', notes: '' }
const money = (value) => `₹${Number(value || 0).toLocaleString('en-IN')}`
export default function TransactionsPage() {
  const { t } = useLanguage(); const [transactions, setTransactions] = useState([]); const [customers, setCustomers] = useState([]); const [form, setForm] = useState(null); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  const load = async () => { setLoading(true); try { const [items, customerData] = await Promise.all([businessService.transactions({ limit: 100 }), businessService.customers({ limit: 100 })]); setTransactions(items); setCustomers(customerData.customers) } catch (e) { toast.error(getApiError(e)) } finally { setLoading(false) } }
  useEffect(() => { const timer = window.setTimeout(() => { load() }, 0); return () => window.clearTimeout(timer) }, [])
  const setType = (transactionType) => setForm(current => ({ ...current, transactionType, paidAmount: transactionType === 'UDHAR' ? '0' : transactionType === 'PARTIAL' ? current.paidAmount : current.totalAmount }))
  const save = async (event) => { event.preventDefault(); setSaving(true); try { await businessService.createTransaction({ ...form, totalAmount: Number(form.totalAmount), paidAmount: Number(form.paidAmount || 0) }); toast.success(t('business.saleAdded')); setForm(null); load() } catch (e) { toast.error(getApiError(e)) } finally { setSaving(false) } }
  return <section className="business-page"><header className="business-heading"><div><p>{t('business.salesBook')}</p><h2>{t('nav.transactions')}</h2></div><button className="action-button" onClick={() => setForm(fresh)}><Plus size={18}/>{t('actions.addSale')}</button></header><div className="record-list">{loading ? <div className="state-card">{t('business.loading')}</div> : transactions.length ? transactions.map(tx => <article className="transaction-card" key={tx._id}><div className="transaction-icon"><ReceiptText size={19}/></div><div><strong>{tx.customer?.name || t('business.customer')}</strong><small>{new Date(tx.transactionDate).toLocaleDateString()} · {tx.transactionType}</small></div><div className="transaction-value"><strong>{money(tx.totalAmount)}</strong><small className={`status ${tx.status?.toLowerCase()}`}>{tx.status?.replace('_', ' ')}</small>{tx.outstanding > 0 && <em>{t('business.due')} {money(tx.outstanding)}</em>}</div></article>) : <div className="state-card"><ReceiptText size={28}/><p>{t('business.noTransactions')}</p></div>}</div>{form && <div className="sheet-backdrop"><form className="entry-sheet" onSubmit={save}><button type="button" className="sheet-close" onClick={() => setForm(null)}><X size={20}/></button><h2>{t('business.newSale')}</h2><label>{t('business.customer')}<select required value={form.customerId} onChange={e => setForm({...form,customerId:e.target.value})}><option value="">{t('business.chooseCustomer')}</option>{customers.map(customer => <option key={customer._id} value={customer._id}>{customer.name}</option>)}</select></label><label>{t('business.amount')}<input required min="1" type="number" inputMode="decimal" value={form.totalAmount} onChange={e => setForm({...form,totalAmount:e.target.value,paidAmount: ['CASH','UPI'].includes(form.transactionType) ? e.target.value : form.paidAmount})}/></label><div className="type-grid">{['CASH','UPI','UDHAR','PARTIAL'].map(type => <button type="button" className={form.transactionType === type ? 'selected' : ''} key={type} onClick={() => setType(type)}>{type}</button>)}</div>{form.transactionType === 'PARTIAL' && <label>{t('business.paidAmount')}<input required min="0" max={form.totalAmount || undefined} type="number" inputMode="decimal" value={form.paidAmount} onChange={e => setForm({...form,paidAmount:e.target.value})}/></label>}<label>{t('business.notes')}<textarea value={form.notes} onChange={e => setForm({...form,notes:e.target.value})}/></label><button className="action-button wide" disabled={saving || !customers.length}>{saving ? t('business.saving') : t('business.saveSale')}</button></form></div>}</section>
}
