export default {
  app: { name: 'Shri Lata Kirana Stores', subtitle: 'Digital Khata' },
  nav: { dashboard: 'Dashboard', customers: 'Customers', transactions: 'Transactions', payments: 'Payments', notifications: 'Notifications', receipts: 'Receipts', settings: 'Settings' },
  actions: { logout: 'Log out', theme: 'Theme', language: 'Language', light: 'Light', dark: 'Dark', viewAll: 'View all', addSale: 'Add sale', collect: 'Collect', addCustomer: 'Add customer', daySummary: 'Day summary' },
  dashboard: { greeting: 'Good morning', welcome: 'Welcome back', shopFallback: 'Your Kirana Store', today: 'Today', sales: "Today's sales", totalOutstanding: 'Total outstanding', overdue: 'Overdue', customers: 'Customers', pendingEntries: 'Pending entries', completeTransactions: 'Review your outstanding customer entries', needsAttention: 'Needs attention', recentActivity: 'Recent activity', noActivity: 'Your recent shop activity will appear here.', noOverdue: 'No overdue payments. Great work!', cash: 'Cash', upi: 'UPI', udhar: 'Udhar' },
  business: { customerBook: 'Customer book', salesBook: 'Sales book', collectionBook: 'Collection book', loading: 'Loading your records…', searchCustomers: 'Search name or mobile number', noCustomers: 'No customers yet. Add your first customer.', noTransactions: 'No sales recorded yet.', noPayments: 'No payments recorded for this customer.', customerAdded: 'Customer added', customerUpdated: 'Customer updated', customerRemoved: 'Customer removed', saleAdded: 'Sale recorded', paymentAdded: 'Payment recorded', newCustomer: 'New customer', editCustomer: 'Edit customer', saveCustomer: 'Save customer', newSale: 'Add sale', saveSale: 'Record sale', newPayment: 'Collect payment', savePayment: 'Save payment', remove: 'Remove', removeCustomer: 'Remove customer', name: 'Name', mobile: 'Mobile number', address: 'Address', creditDays: 'Credit period (days)', notes: 'Notes', customer: 'Customer', chooseCustomer: 'Choose customer', amount: 'Amount', paidAmount: 'Paid now', due: 'Due', addPayment: 'Collect', selectCustomer: 'Select a customer', saving: 'Saving…', daysOverdue: 'days overdue' },
  shop: { welcome: 'One-time setup', title: 'Set up your shop', description: 'Add your shop details once to start managing customers, sales, and payments.', shopName: 'Shop name', shopNameExample: 'Shri Lata Kirana Stores', ownerName: 'Owner name', mobile: 'Shop mobile number', address: 'Shop address', addressExample: 'Pune, Maharashtra', creditPeriod: 'Default credit period', noCredit: 'No credit', days: 'days', create: 'CREATE MY SHOP', creating: 'Creating your shop…', created: 'Your shop is ready!' },
  pages: { comingSoon: 'Coming soon', modulePlaceholder: 'This module is ready for its next build phase.', settings: 'Settings' },
  auth: { loading: 'Loading your account…' },
}
